import type { Metadata } from "next";
import MenuShowerCabine from "@/components/MenuShowerCabine";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full mx-auto  flex flex-col   h-dvh ">
          <header className="flex  justify-center items-center    text-center  bg-white dark:bg-slate-900 sticky top-18 z-20 ">
            {/* <header className="flex  justify-center items-center    text-center  bg-white dark:bg-slate-900 "> */}
            <MenuShowerCabine />
          </header>
          <main className="flex justify-center items-start">{children}</main>
        </div>
      </body>
    </html>
  );
}
