import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { MenuFooter } from "@/components/MenuFooter";
// import Link from "next/link";
import ShakingPhone from "@/components/ShakingPhone";
// import MenuHeader from "@/components/MenuHeader";
import { Codesandbox } from "lucide-react";
import { Menu } from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="w-7xl mx-auto  flex flex-col justify-between   h-dvh ">
          <header className="flex  justify-start items-center    text-center border-2 border-blue-400 sticky top-0 bg-white dark:bg-slate-900 z-50 ">
            <div className=" flex max-w-sm items-center gap-x-4  bg-white py-2  dark:bg-slate-800  ">
              <Codesandbox className="h-10 w-10 text-neutral-600 dark:text-neutral-300 aspect-square rounded-full bg-gray-200 dark:bg-neutral-800" />
              <div>
                <div className="text-xl font-medium text-black dark:text-white">
                  <h1>LOGO Header </h1>
                </div>
                <p className="text-center text-gray-500 dark:text-gray-400">
                  our device!
                </p>
              </div>
            </div>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Menu />
            </ThemeProvider>
          </header>
          <main className="flex justify-center items-start">{children}</main>
          {/* <main className="flex  items-start justify-start">{children}</main> */}
          <footer className="flex justify-between items-center  ">
            <div className="flex">
              <div className=" relative ">
                <div className="  z-20 ">
                  {/* <div className="absolute bottom-6 left-4 z-20 "> */}
                  {/* <Phone size={24} fill="red" /> */}
                  <ShakingPhone />
                </div>
              </div>
            </div>
            <div className="flex">
              <div className="relative  border-2 border-orange-300">
                {/* <div className="relative mb-8 border-2 border-orange-300"> */}
                <div className="absolute bottom-0 right-6 z-10 ">
                  {/* <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    <MenuFooter />
                  </ThemeProvider> */}
                </div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
