import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MenuFooter } from '@/components/MenuFooter';
import Link from 'next/link';
import ShakingPhone from '@/components/ShakingPhone';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          {/* <nav>
            <Link href="/">About</Link>
            <Link href="/cabine">Cabine</Link>
            <Link href="/fence">Fence</Link>
            <Link href="/canopy">Canopy</Link>
            <Link href="/partition">Partition</Link>
          </nav> */}
        </header>
        <main>{children}</main>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <footer className="flex  items-center justify-center mt-10 mb-16 ">
            {/* <ShakingPhone /> */}
            <MenuFooter />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
